### ISSUE TITLE
Docs Site Overrides ⌘-F

### ISSUE THREAD

**Issue by cholick** [cloudfoundry/docs-cfcr#10]
⌘-F to find in page is one of my most-used shortcuts. Overriding the default browser behavior 
creates a bad experience using the site.

**Comment by bentarnoff** [comment]
Thanks, @cholick. It looks like this was a "feature" of `mkdocs-material` which got eliminated in the most recent version. However, the Docker image that has `mkdocs-material`, which our pipelines use to build the site, doesn't seem to be pulling in the latest version. I'm not totally sure how to fix that, but if you have thoughts, please let us know!

**Comment by cholick** [comment]
Ah, then it'll go away eventually as new builds filter through. Will just close this out and wait :)
