### ISSUE TITLE
Undefined stars, undefined forks on docs-kubo.cfapps.io

### ISSUE THREAD

**Issue by girikuncoro** [cloudfoundry/docs-cfcr#15]
I was reading the docs through https://docs-kubo.cfapps.io and found at the top right corner: undefined stars undefined forks

![image](https://user-images.githubusercontent.com/3192347/32910755-f6e832e4-cabe-11e7-89cc-cb07e5ef152f.png)

**Comment by bentarnoff** [comment]
Hey @girikuncoro when I look at docs-kubo.cfapps.io I see 4 stars and 7 forks. 
![screen shot 2017-11-16 at 1 56 08 pm](https://user-images.githubusercontent.com/14351981/32918067-f9ccc40e-cad5-11e7-868d-d95397046ee6.png)

**Comment by girikuncoro** [comment]
hmm interesting, now I'm also able to see it.
![image](https://user-images.githubusercontent.com/3192347/32932775-b57d07f8-cb1d-11e7-8b51-cd6f4da4db42.png)

cool then I'll close this
