### ISSUE TITLE
director.yml - master_target_pool?

### ISSUE THREAD

**Issue by guillierf** [cloudfoundry/docs-cfcr#17]
in the director.yml file, the meaning of the field is not very clear:

master_target_pool: # target pool that master nodes will be a part of

Is it possible to provide more info on this field and an example?

**Comment by bentarnoff** [comment]
@gregpatricio Can you speak to this?

**Comment by gregpatricio** [comment]
@guillierf Thanks for your input. 
This property will actually be removed shortly. CFCR is now deploying in a single master configuration, with ETCD colocated in this master node, which means that the master_target_pool property is not needed anymore.

**Comment by bentarnoff** [comment]
Thanks @gregpatricio. I'm closing this issue because this property will soon be removed and the docs updated accordingly.
