### ISSUE TITLE
not clear - vSphere hostname can be resolved using 8.8.8.8 as the nameserver

### ISSUE THREAD

**Issue by guillierf** [cloudfoundry/docs-cfcr#18]
From this link:
https://docs-cfcr.cfapps.io/installing/vsphere/deploying-bosh-vsphere/

This part is not very clear:

"Ensure your vSphere hostname can be resolved using 8.8.8.8 as the nameserver. For example:

$ dig @8.8.8.8 ab2-host-a101-11.foo-12.bar.cf-example.com

If the hostname cannot be resolved, open ~/kubo-deployment/bosh-deployment/bosh.yml and locate the dns property. Replace 8.8.8.8 with the nameserver of your vSphere environment.
"

What does 'vSphere hostname' mean?
is it the vCenter - or ESXi host - or VM name?

**Comment by bentarnoff** [comment]
@gregpatricio Could you comment on the above? Thanks.

**Comment by gregpatricio** [comment]
@guillierf The docs are not clear as you say. "vSphere hostname" should be "vCenter hostname".
Thanks!

**Comment by bentarnoff** [comment]
Thanks @gregpatricio @guillierf. We've updated the docs accordingly.
