### ISSUE TITLE
HA Proxy is not supported as of CFCR 0.10

### ISSUE THREAD

**Issue by akshaymankar** [cloudfoundry/docs-cfcr#23]
The docs still show how to configure it. Maybe we should remove all references to HAProxy from the docs.

**Comment by bentarnoff** [comment]
Thanks @akshaymankar. @gregpatricio @glestaris what do you think?

**Comment by glestaris** [comment]
hey @bentarnoff, I prioritised https://www.pivotaltracker.com/story/show/153598537

**Comment by glestaris** [comment]
hey @bentarnoff, I prioritised https://www.pivotaltracker.com/story/show/153598537

**Comment by bentarnoff** [comment]
Thanks, @glestaris !
