### ISSUE TITLE
CFCR 0.11 - Missing service account info?

### ISSUE THREAD

**Issue by neil-hickey** [cloudfoundry/docs-cfcr#28]
I deployed CFCR 0.11 to GCP yesterday following the cfcr docs, the deployment failed due to the service account being `null` in the `cloud config`.

I didn't notice any steps in the docs to add my service key for gcp, or set the service account for master and worker. Once i manually edited the cloud config and added my service account, the deployment was successful.

**Comment by mjgutermuth** [comment]
Hi @neil-hickey! Were you following the steps in [Deploying BOSH for CFCR on GCP](http://docs-cfcr.cfapps.io/installing/gcp/deploying-bosh-gcp/#step-2-set-up-a-gcp-account-for-terraform)? I see a step for creating a Terraform service account and key. Is this the key you had to add manually to the cloud config?

**Comment by neil-hickey** [comment]
hi @mjgutermuth, yep these are the steps. The actual failure happened when creating a cluster though. This is the service account I added, but I think maybe there should be a separate account for the worker and master vms? That was my understanding, to get it working I added this account to both, but I am not sure this is strictly correct, they probably should have different permissions if they are explicitly separated?

**Comment by mjgutermuth** [comment]
Gotcha. I'll follow up with someone from CFCR and we'll update the docs accordingly. Thanks for pointing this out!

**Comment by mjgutermuth** [comment]
Hey @neil-hickey, you're right -- according to the CFCR team, there should be separate service accounts for the worker and master VMs. The Terraform script creates both accounts:

* https://github.com/cloudfoundry-incubator/kubo-deployment/blob/v0.11.0/docs/user-guide/platforms/gcp/kubo-infrastructure.tf#L46-L54
* https://github.com/cloudfoundry-incubator/kubo-deployment/blob/v0.11.0/docs/user-guide/platforms/gcp/kubo-infrastructure.tf#L248-L249
