### ISSUE TITLE
disk depricated in google compute engine

### ISSUE THREAD

**Issue by haugom** [cloudfoundry/docs-cfcr#5]
Hi

I was trying kubo out on gce tonight and experienced two errors:
```
2 error(s) occurred:

* google_compute_instance.bosh-bastion: "disk": [REMOVED] Use boot_disk, scratch_disk, and attached_disk instead
* google_compute_instance.nat-instance-private-with-nat-primary: "disk": [REMOVED] Use boot_disk, scratch_disk, and attached_disk instead
```

I fixed this by changing the kubo-infrastructure.tf `disk {}` block to

```
  boot_disk {
    initialize_params {
      image = "${var.latest_ubuntu}"
    }
  }
```
This was in the `Create the bastion and other resources. Enter the following command...`

**Comment by bentarnoff** [comment]
Hey @haugom thanks for bringing this to our attention. This is a deprecated property in Terraform that has been finally removed. We have updated our Kubo scripts accordingly. Please update your kubo-deployment artifact and retry. We will also add information to the Troubleshooting topic.
