### ISSUE TITLE
Are these instructions deprecated?

### ISSUE THREAD

**Issue by mariash** [cloudfoundry/docs-cfcr#59]
I was told that these instructions might be deprecated as well as all the scripts. And instead to use https://github.com/cloudfoundry-incubator/kubo-release. It would be nice to see a deprecation message so that people don't follow these instructions.

**Comment by bentarnoff** [comment]
Thanks @mariash. @alex-slynko can you speak to the above?

**Comment by alex-slynko** [comment]
Hi @mariash 
The instructions, as well as scripts, are deprecated. Where would you put the deprecation notice?
We put one in README and the front page of the docs. We might send an email to cf-dev, but I'm not sure about it.

**Comment by mariash** [comment]
@alex-slynko I would put it on every page of the docs. When you google CFCR it just drops you on one of the pages and you start following it, since everything looks legit. For example, https://docs-cfcr.cfapps.io/installing/gcp/

I saw the deprecation warning in the README of kubo-release too, but it was too late lol.

**Comment by mariash** [comment]
@alex-slynko Does it make sense to keep these docs even? maybe they should be removed completely?

**Comment by alex-slynko** [comment]
Hey @mariash 
We have created a story in our backlog and will delete all unused parts soon.

**Comment by bentarnoff** [comment]
Closing because CFCR docs are being redone.
