### ISSUE TITLE
L Error: Instance group 'master' must specify availability zone that matches availability zones of network 'default' Task 44 | 10:09:18 | Error: Instance group 'master' must specify availability zone that matches availability zones of network 'default'

### ISSUE THREAD

**Issue by kanchoud** [cloudfoundry/docs-cfcr#73]

**Comment by bentarnoff** [comment]
Thanks @kanchoud. @bstick12 is this something you might be able to help with?

**Comment by bstick12** [comment]
Hi @kanchoud ,

Can you please verify that you have fulfilled the pre-requisites as detailed at - https://github.com/cloudfoundry-incubator/kubo-release/#prerequisites

From the error message you are receiving it looks like your default network has different availability zones configured that the ones being requested by the CFCR deployment.

If you are still having issues can you open a defect under the https://github.com/cloudfoundry-incubator/kubo-deployment using the template and providing the requested information.

**Comment by kanchoud** [comment]
I am trying to setup CFCR on AWS.
I have completed with bosh deployment.
After configuring BOSH, you can deploy the CFCR BOSH release. 
I am following this link
https://github.com/cloudfoundry-incubator/kubo-release/#prerequisites

when i execute this command
cd kubo-deployment

bosh deploy -d cfcr manifests/cfcr.yml \
  -o manifests/ops-files/misc/single-master.yml \
  -o manifests/ops-files/add-hostname-to-master-certificate.yml \
  -v api-hostname=[DNS-NAME]

i am facing this issue
 Error: Instance group 'master' must specify availability zone that matches availability zones of network 'default'
